[ec2_target]
devops-uws-b01813057.duckdns.org ansible_user=ubuntu

[staging]
ec2-staging ansible_host=devops-uws-b01813057.duckdns.org ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/devops-rsa.pem