---
- name: Provision new staging EC2 instance
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    region: "us-east-1"
    instance_type: "t2.micro"
    image_id: "ami-0b6c6ebed2801a5cb"
    key_name: "devops-rsa"
    security_group_name: "launch-wizard-3"

  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: "Assignment2-CD-Prod"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image_id }}"
        region: "{{ region }}"
        security_groups:
          - "{{ security_group_name }}"
        tags:
          Name: "Assignment2-CD-Prod"
        wait: true
        count: 1
        state: running
      register: ec2_result